---
baseURL: https://referok.com
languageCode: en-us
title: referok.com
pygmentsstyle: monokai
metaDataFormat: yaml
module:
  imports:
  - path: github.com/brewmanandi/hugo-theme-novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
